version: "3.1"
services:
  app:
    build: .
    command: python3 -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27016:27017 
    volumes:
      - db:${REL_PATH}/db
volumes:
  db:
