version: '3.4'

services:
  db:
    image: mongo
    hostname: mongodb
    environment:
      MONGO_INITDB_DATABASE: spotifydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - db-data:/etc/data
    ports:
      - 27018:27017 
  devopsapp:
    image: devopsapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
volumes:
  db-data: