version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - db:./db
    ports:
      - 27017:27017 
volumes:
  db:
