version: "3.1"
services:
<<<<<<< HEAD
  app:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
=======
  # app:
  #   build: .
  #   command: python3 -u app.py
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/app
  #   links:
  #     - db
  #   networks:
  #     - app-network
  db:
    image: mongo
    hostname: mongodb
    environment:
      MONGO_INITDB_DATABASE: spotifydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - db-data:/etc/data
    ports:
      - 27018:27017 
volumes:
  db-data:
>>>>>>> origin/main
