version: "3.1"
services:
  app:
    build: .
    command: python3 -u app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - backend
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017 
    volumes:
      - db:${REL_PATH}/db
    networks:
      - backend
volumes:
  db:
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
